require('./highlight/highlight.pack.js')
require('style!css!./highlight/styles/default.css')
require('style!css!./highlight/styles/solarized-dark.css')
require('style!css!./highlight/styles/solarized-light.css')
require('style!css!./highlight/styles/github.css')
require('style!css!./highlight/styles/railscasts.css')
require('style!css!./highlight/styles/monokai-sublime.css')
require('style!css!./highlight/styles/mono-blue.css')
require('style!css!./highlight/styles/tomorrow.css')
require('style!css!./highlight/styles/color-brewer.css')
require('style!css!./highlight/styles/zenburn.css')
require('style!css!./highlight/styles/agate.css')
require('style!css!./highlight/styles/androidstudio.css')
require('style!css!./highlight/styles/dracula.css')
require('style!css!./highlight/styles/rainbow.css')
require('style!css!./highlight/styles/vs.css')
require('style!css!./highlight/styles/atom-one-dark.css')
require('style!css!./highlight/styles/atom-one-light.css')
// console.log(hljs)

hljs.initHighlightingOnLoad()
